@startuml traingame

object traingame
    object track
        object lenght
    object train
        object bagoons
            object maxWight
        object mainBagoon
            object motorForce
        object passengerBagoon
        object actions{
            accelerate
            stop
            clackson
        }
    object player
        object name
        object playerActions{
            moveTrain
            stopTrain
            soundClackson
        }

traingame *-- track
traingame *-- train
traingame *-- player

track *-- lenght
track o-right- train

train *-- bagoons
train *-- mainBagoon
train *-- passengerBagoon

bagoons *-- maxWight

mainBagoon *-- motorForce
mainBagoon -left-|> bagoons

train o-- actions
player *-- playerActions

player o-right- name
player -left-> train

@enduml